// ============================================
// FILE: lib/firebase_options.dart
// ============================================
// This file will be auto-generated by FlutterFire CLI
// For now, we'll create it manually

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ANDROID CONFIG

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvyWW4z_7lsnIesBuIXLV2Csc_ttFSnko',
    appId: '1:706814716072:android:a8d36674dbd7bba6eaba9d',
    messagingSenderId: '706814716072',
    projectId: 'aamaly-fyp-31b81',
    storageBucket: 'aamaly-fyp-31b81.firebasestorage.app',
  );

  // You'll get these values from your google-services.json

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1tyYemO7g43ZhKU9n61x468titG3YYNQ',
    appId: '1:706814716072:ios:5b1e525901b8220deaba9d',
    messagingSenderId: '706814716072',
    projectId: 'aamaly-fyp-31b81',
    storageBucket: 'aamaly-fyp-31b81.firebasestorage.app',
    iosBundleId: 'com.example.aamalyApp',
  );

  // iOS CONFIG (if you added iOS)

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMaERSB0dIudLjXdUApfgq1FKkP0SrUP4',
    appId: '1:706814716072:web:4ecb4cb8f225f966eaba9d',
    messagingSenderId: '706814716072',
    projectId: 'aamaly-fyp-31b81',
    authDomain: 'aamaly-fyp-31b81.firebaseapp.com',
    storageBucket: 'aamaly-fyp-31b81.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1tyYemO7g43ZhKU9n61x468titG3YYNQ',
    appId: '1:706814716072:ios:5b1e525901b8220deaba9d',
    messagingSenderId: '706814716072',
    projectId: 'aamaly-fyp-31b81',
    storageBucket: 'aamaly-fyp-31b81.firebasestorage.app',
    iosBundleId: 'com.example.aamalyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMaERSB0dIudLjXdUApfgq1FKkP0SrUP4',
    appId: '1:706814716072:web:de39266f9e941451eaba9d',
    messagingSenderId: '706814716072',
    projectId: 'aamaly-fyp-31b81',
    authDomain: 'aamaly-fyp-31b81.firebaseapp.com',
    storageBucket: 'aamaly-fyp-31b81.firebasestorage.app',
  );

}

// IMPORTANT: We'll use FlutterFire CLI to auto-generate this file properly
// For now, this is a placeholder structure